# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/getAllPosts
Accept: application/json

###

GET http://localhost:8080/getPost/2
Accept: application/json

###

POST http://localhost:8080/addPost
Content-Type: application/json

{
  "userId": "1",
  "title": "TestTitle 1",
  "content": "TestContent 1"
}

###

PUT http://localhost:8080/modifyPost
Content-Type: application/json

{
  "id": "2",
  "userId": "1",
  "title": "TestTitle Modify",
  "content": "TestContent Modify"
}

###

DELETE http://localhost:8080/deletePost/1
Accept: application/json

###
###

GET http://localhost:8080/getAllUsers
Accept: application/json

###

GET http://localhost:8080/getUser/2
Accept: application/json

###

POST http://localhost:8080/addUser
Content-Type: application/json

{
  "account": "Test Account",
  "password": "Test Password",
  "username": "Test Username",
  "email": "Test Email"
}

###

PUT http://localhost:8080/modifyUser
Content-Type: application/json

{
  "id": "2",
  "password": "password Modify",
  "username": "username Modify",
  "email": "email Modify"
}

###

DELETE http://localhost:8080/deleteUser/1
Accept: application/json

###